CREATE DATABASE QUANLY_NHASACH
GO
--DROP DATABASE QUANLY_NHASACH_
USE QUANLY_NHASACH
GO

--====================TẠO BẢNG================-
--TÀI KHOẢN QUẢN LÝ 
CREATE TABLE TK_QUANLY
(
	MAQL		VARCHAR(10),
	MATKHAU		NVARCHAR(60),
	CONSTRAINT PK_TKQL PRIMARY KEY (MAQL)
)
--TÀI KHOẢN NHÂN VIÊN
CREATE TABLE TK_NHANVIEN
(
	MANV		VARCHAR(10),
	MATKHAU		NVARCHAR(60),
	CONSTRAINT PK_TKNV PRIMARY KEY (MANV)
)
--NHÂN VIÊN 
CREATE TABLE NHANVIEN
(
	MANV		VARCHAR(10),
	TENNV		NVARCHAR(60),
	NGAYSINH	DATE,
	GIOITINH	NVARCHAR(5),
	CMND		VARCHAR(12),
	DIACHI		NVARCHAR(200),
	SDT			VARCHAR(12),
	CONSTRAINT PK_NHANVIEN PRIMARY KEY(MANV),
	CONSTRAINT FK_NHANVIEN_TKNV FOREIGN KEY(MANV) REFERENCES TK_NHANVIEN(MANV)

)
--KHO HÀNG
CREATE TABLE KHOHANG
(
	MAKHO		VARCHAR(10),
	TENKHO		NVARCHAR(200),
	DIACHI		NVARCHAR(200),
	SDT			VARCHAR(12),
	GHICHU		NVARCHAR(100)
	CONSTRAINT PK_KHOHANG PRIMARY KEY (MAKHO)
)
--NHÀ CUNG CẤP 
CREATE TABLE NHACUNGCAP
(
	MANCC		VARCHAR(10),
	TENNCC		NVARCHAR(200),
	DIACHI		NVARCHAR(200),
	SDT			VARCHAR(12),
	FAX			VARCHAR(10),
	EMAIL		NVARCHAR(100),
	CONSTRAINT PK_NHACUNGCAP PRIMARY KEY (MANCC)
)
--TÁC GIẢ 
CREATE TABLE TACGIA
(
	MATGCHINH	VARCHAR(10),
	TENTGCHINH	NVARCHAR(60),
	CONSTRAINT PK_TACGIA PRIMARY KEY(MATGCHINH)
)
--NHÀ XUẤT BẢN 
CREATE TABLE NHAXUATBAN
(
	MANXB		VARCHAR(10),
	TENNXB		NVARCHAR(100),
	CONSTRAINT PK_NXB PRIMARY KEY(MANXB)
)
--KHÁCH HÀNG
CREATE TABLE KHACHHANG
(
	MAKH		VARCHAR(10),
	TENKH		NVARCHAR(60),
	GIOITINH	NVARCHAR(5),
	DIACHI		NVARCHAR(200),
	SDT			VARCHAR(12),
	EMAIL		NVARCHAR(100),
	CONSTRAINT PK_KHACHHANG PRIMARY KEY (MAKH)
)
--SÁCH 
CREATE TABLE SACH
(
	MASH		VARCHAR(10),
	TENSH		NVARCHAR(100),
	THELOAI		NVARCHAR(50),
	GIA			FLOAT,
	SLTONKHO	INT,
	MANXB		VARCHAR(10),
	MATGCHINH	VARCHAR(10),
	MAKHO		VARCHAR(10),
	CONSTRAINT PK_SACH PRIMARY KEY(MASH),
	CONSTRAINT FK_SACH_NXB FOREIGN KEY(MANXB) REFERENCES NHAXUATBAN(MANXB),
	CONSTRAINT FK_SACH_TACGIA FOREIGN KEY(MATGCHINH) REFERENCES TACGIA(MATGCHINH),
	CONSTRAINT FK_SACH_KHO FOREIGN KEY(MAKHO) REFERENCES KHOHANG(MAKHO)
)
--PHIẾU NHẬP 
CREATE TABLE PHIEUNHAP
(
	MAPN		VARCHAR(10) ,
	MANV		VARCHAR(10),
	MANCC		VARCHAR(10),
	NGAYNHAP	DATETIME,
	CONSTRAINT PK_PHIEUNHAP PRIMARY KEY(MAPN),
	CONSTRAINT FK_PN_NV FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV),
	CONSTRAINT FK_PN_NCC FOREIGN KEY(MANCC) REFERENCES NHACUNGCAP(MANCC)
)
--CHI TIẾT PHIẾU NHẬP 
CREATE TABLE CHITIETPHIEUNHAP
(
	MAPN		VARCHAR(10) ,
	MASH		VARCHAR(10),
	SOLUONG		INT,
	DONGIA		FLOAT,
	THANHTIEN	FLOAT,
	CONSTRAINT PK_CTPN PRIMARY KEY(MAPN,MASH),
	CONSTRAINT FK_CTPN_PN FOREIGN KEY(MAPN) REFERENCES PHIEUNHAP(MAPN),
	CONSTRAINT FK_CTPN_SACH FOREIGN KEY(MASH) REFERENCES SACH(MASH)
)
--HÓA ĐƠN
CREATE TABLE HOADON 
(
	MAHD		VARCHAR(10),
	MAKH		VARCHAR(10),
	MANV		VARCHAR(10),
	NGAYXUATHD	DATETIME,
	CONSTRAINT PK_HOADON PRIMARY KEY(MAHD),
	CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH),
	CONSTRAINT FK_HOADON_NHANVIEN FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)
)
--CHI TIẾT HÓA ĐƠN 
CREATE TABLE CHITIET_HOADON
(
	MAHD		VARCHAR(10) ,
	MASH		VARCHAR(10),
	SOLUONG		INT,
	DONGIA		FLOAT,
	THANHTIEN	FLOAT,
	CONSTRAINT PK_CTHD PRIMARY KEY(MAHD,MASH),
	CONSTRAINT FK_CTHD_HOADON FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
	CONSTRAINT FK_CTHD_SACH FOREIGN KEY (MASH) REFERENCES SACH(MASH)
)
--KHU VỰC
CREATE TABLE KHUVUC 
(
	MAKV		VARCHAR(10),
	MASH		VARCHAR(10),
	VITRIKE		NVARCHAR(50),
	LAU			INT,
	CONSTRAINT PK_KHUVUC PRIMARY KEY (MAKV),
	CONSTRAINT FK_KHUVUC_SACH FOREIGN KEY (MASH) REFERENCES SACH(MASH)
)

-- Sách
ALTER TABLE SACH ALTER COLUMN GIA DECIMAL(18, 2) NOT NULL;

-- Chi tiết phiếu nhập
ALTER TABLE CHITIETPHIEUNHAP ALTER COLUMN DONGIA DECIMAL(18, 2) NOT NULL;
ALTER TABLE CHITIETPHIEUNHAP ALTER COLUMN THANHTIEN DECIMAL(18, 2) NOT NULL;

-- Chi tiết hóa đơn
ALTER TABLE CHITIET_HOADON ALTER COLUMN DONGIA DECIMAL(18, 2) NOT NULL;
ALTER TABLE CHITIET_HOADON ALTER COLUMN THANHTIEN DECIMAL(18, 2)  NOT NULL;

-- Tổng tiền hóa đơn
ALTER TABLE HOADON ADD TONGTIEN DECIMAL(18, 2) DEFAULT 0;


--===============-TRIGGER - PROCEDURE- FUNCTION==================
--CREATE FUNCTION AUTO_IDSACH()
--RETURNS VARCHAR(10)
--AS
--BEGIN
--	DECLARE @ID VARCHAR(10)
--	IF (SELECT COUNT(MASH) FROM SACH) = 0
--		SET @ID = '0'
--	ELSE
--		SELECT @ID = MAX(RIGHT(MASH, 3)) FROM SACH
--		SELECT @ID = CASE
--			WHEN @ID >= 0 and @ID < 9 THEN 'SH00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
--			WHEN @ID >= 9 THEN 'SH0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
--		END
--	RETURN @ID
--END
--ALTER TABLE SACH 
-- ADD CONSTRAINT IDSACH DEFAULT DBO.AUTO_IDSACH()
------------------------------------------------------------

CREATE TRIGGER TRG_CAPNHAT_TONKHO_NHAP
ON CHITIETPHIEUNHAP
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;

    -- Tính chênh lệch số lượng theo từng MASH
    WITH ThayDoi AS (
        SELECT 
            COALESCE(i.MASH, d.MASH) AS MASH,
            ISNULL(SUM(i.SOLUONG), 0) - ISNULL(SUM(d.SOLUONG), 0) AS ChenhLech
        FROM inserted i
        FULL OUTER JOIN deleted d 
            ON d.MAPN = i.MAPN AND d.MASH = i.MASH
        GROUP BY COALESCE(i.MASH, d.MASH)
    )
    -- Cập nhật tồn kho trong bảng SACH
    UPDATE SACH
    SET SLTONKHO = SACH.SLTONKHO + TD.ChenhLech
    FROM SACH
    INNER JOIN ThayDoi TD ON SACH.MASH = TD.MASH;

    -- (Tùy chọn) Kiểm tra tồn kho âm - hiếm khi xảy ra với nhập hàng nhưng vẫn nên có
    IF EXISTS (SELECT 1 FROM SACH WHERE SLTONKHO < 0)
    BEGIN
        RAISERROR(N'Lỗi: Tồn kho bị âm sau thao tác nhập hàng!', 16, 1);
        ROLLBACK TRANSACTION;
    END
END
GO


CREATE TRIGGER TRG_CAPNHAT_TONKHO_BAN
ON CHITIET_HOADON
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;

    -- Tạo bảng tạm chứa chênh lệch số lượng bán theo từng MASH
    SELECT 
        COALESCE(i.MASH, d.MASH) AS MASH,
        ISNULL(SUM(i.SOLUONG), 0) - ISNULL(SUM(d.SOLUONG), 0) AS SoLuongBan
    INTO #ThayDoi
    FROM inserted i
    FULL OUTER JOIN deleted d 
        ON d.MAHD = i.MAHD AND d.MASH = i.MASH
    GROUP BY COALESCE(i.MASH, d.MASH);

    -- Kiểm tra tồn kho không đủ → rollback nếu có
    IF EXISTS (
        SELECT 1
        FROM #ThayDoi TD
        INNER JOIN SACH S ON S.MASH = TD.MASH
        WHERE TD.SoLuongBan > 0 AND S.SLTONKHO < TD.SoLuongBan
    )
    BEGIN
        DECLARE @TenSach NVARCHAR(100);
        SELECT TOP 1 @TenSach = S.TENSH
        FROM #ThayDoi TD
        INNER JOIN SACH S ON S.MASH = TD.MASH
        WHERE TD.SoLuongBan > 0 AND S.SLTONKHO < TD.SoLuongBan;

        DROP TABLE #ThayDoi;  -- Dọn dẹp trước khi rollback

        RAISERROR(N'Không đủ tồn kho để bán! Sách "%s" hoặc một số sách khác hiện không đủ số lượng.', 16, 1, @TenSach);
        ROLLBACK TRANSACTION;
        RETURN;
    END

    -- Cập nhật tồn kho thực tế
    UPDATE SACH
    SET SLTONKHO = SACH.SLTONKHO - TD.SoLuongBan
    FROM SACH
    INNER JOIN #ThayDoi TD ON SACH.MASH = TD.MASH
    WHERE TD.SoLuongBan > 0;

    -- Dọn dẹp bảng tạm
    DROP TABLE #ThayDoi;
END
GO

CREATE TRIGGER TRG_UPDATE_TONGTIEN_HD
ON CHITIET_HOADON
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE HOADON
    SET TONGTIEN = ISNULL((
        SELECT SUM(THANHTIEN)
        FROM CHITIET_HOADON ct
        WHERE ct.MAHD = HOADON.MAHD
    ), 0)
    WHERE MAHD IN (
        SELECT MAHD FROM inserted
        UNION
        SELECT MAHD FROM deleted
    );
END
GO