USE QUANLY_NHASACH


--NHẬP DỮ LIỆU TÀI KHOẢN ADMIN
INSERT INTO TK_QUANLY VALUES ('admin','admin123') 
--INSERT INTO TK_QUANLY VALUES ('admin1','1234')

--NHẬP DỮ LIỆU KHÁCH HÀNG
INSERT INTO KHACHHANG VALUES ('KH001',N'HOÀNG VĂN TÙNG', N'NAM', N'1808_VĨNH LỘC A, BÌNH CHÁNH ,TPHCM','0964355002','hvt@gmail.com')
INSERT INTO KHACHHANG VALUES ('KH002',N'NGUYỄN VĂN TUẤN', N'NAM', N'QUẬN 1,TPHCM','0964355002','nvt@gmail.com')
--INSERT INTO KHACHHANG VALUES ('KH003',N'HOÀNG VĂN THƯỢNG', N'NAM', N'140 LÊ TRỌNG TẤN, TÂN PHÚ ,TPHCM','0964355003','nvt@gmail.com')
--INSERT INTO KHACHHANG VALUES ('KH004',N'HOÀNG VĂN HẢI', N'NAM', N'145 LÊ TRỌNG TẤN- TÂN PHÚ ,TPHCM','0964355002','nvt@gmail.com')

--NHẬP DỮ LIỆU TÁC GIẢ
INSERT INTO TACGIA VALUES ('TOHUU',N'TỐ HỮU')
INSERT INTO TACGIA VALUES ('NAMCAO',N'NAM CAO')
INSERT INTO TACGIA VALUES ('NGUYENDU',N'NGUYỄN DU')
INSERT INTO TACGIA VALUES ('NGOTATTO',N'NGÔ TẤT TỐ')
INSERT INTO TACGIA VALUES ('VTP',N'VŨ TRỌNG PHỤNG')
INSERT INTO TACGIA VALUES ('NGUYENHONG',N'NGUYÊN HỒNG')
INSERT INTO TACGIA VALUES ('KIMLAN',N'KIM LÂN')
INSERT INTO TACGIA VALUES ('THACHLAM',N'THẠCH LAM')
INSERT INTO TACGIA VALUES ('NGUYENTUAN',N'NGUYỄN TUÂN')
INSERT INTO TACGIA VALUES ('TOHOAI',N'TÔ HOÀI')

--NHẬP DỮ LIỆU NHÀ XUẤT BẢN 
INSERT INTO NHAXUATBAN VALUES ('NXBTRE',N'NHÀ XUẤT BẢN TRẺ')
INSERT INTO NHAXUATBAN VALUES ('NXBKD',N'NHÀ XUẤT BẢN KIM ĐỒNG')
INSERT INTO NHAXUATBAN VALUES ('NXBHNV',N'NHÀ XUẤT BẢN HỘI NHÀ VĂN')
INSERT INTO NHAXUATBAN VALUES ('NXBPN',N'NHÀ XUẤT BẢN PHỤ NỮ VN')
INSERT INTO NHAXUATBAN VALUES ('NXBLD',N'NHÀ XUẤT BẢN LAO ĐỘNG')
INSERT INTO NHAXUATBAN VALUES ('NXBNN',N'NHÀ XUẤT BẢN NHÃ NAM')
INSERT INTO NHAXUATBAN VALUES ('NXBVH',N'NHÀ XUẤT BẢN VĂN HỌC')

--NHẬP DỮ LIỆU KHO HÀNG
INSERT INTO KHOHANG VALUES ('KHO1',N'KHO SÁCH FAHASHA',N'CoopMart Lý Thường Kiệt,497 Hòa Hảo,P.7,Quận 10,TP.HCM','0633885546','...')
INSERT INTO KHOHANG VALUES ('KHO2',N'KHO SÁCH KIM ĐỒNG ',N'11 Sư Vạn Hạnh,Phường 12,Quận 10,TP.HCM','0888 023 688','...')

--NHẬP DỮ LIỆU NHÀ CUNG CẤP
INSERT INTO NHACUNGCAP VALUES ('1',N'KHO SÁCH FAHASHA',N'CoopMart Lý Thường Kiệt,497 Hòa Hảo,P.7,Quận 10,TP.HCM','0633885546','012345678','FAHASHA@GMAIL.COM')
INSERT INTO NHACUNGCAP VALUES ('2',N'KHO SÁCH KIM ĐỒNG ',N'11 Sư Vạn Hạnh,Phường 12,Quận 10,TP.HCM','0888 023 688','012312314','kimdong1@gmail.com')

--NHẬP DỮ LIỆU SÁCH
INSERT INTO SACH VALUES ('1',N'LÃO HẠC',N'Truyện ký',100000,500,'NXBVH','NAMCAO','KHO1')
--NHẬP DỮ LIỆU KHU VỰC
INSERT INTO KHUVUC VALUES ('KV01','1',N'KỆ SÁCH VĂN HỌC',1)

--NHẬP DỮ LIỆU TÀI KHOẢN NHÂN VIÊN 
INSERT INTO TK_NHANVIEN VALUES ('NV01','123456') 
INSERT INTO TK_NHANVIEN VALUES ('NV02','123456')

--NHẬP DỮ LIỆU NHÂN VIÊN
SET DATEFORMAT DMY
INSERT INTO NHANVIEN VALUES ('NV01',N'ĐỖ VĂN THAO','02/07/2002',N'NAM','20010221023',N'1808 VĨNH LỘC A, BÌNH CHÁNH, TPHCM','0964350515') 
INSERT INTO NHANVIEN VALUES ('NV02',N'TRINH THÀNH HIỆP','02/07/2002',N'NAM','20010221023',N'1808 VĨNH LỘC A, BÌNH CHÁNH, TPHCM','0964350515') 


--nHẬP PHIẾU NHẬP 
SET DATEFORMAT DMY
INSERT INTO PHIEUNHAP VALUES ('1','NV01','1','20/12/2022')

--CHI TIẾT PHIẾU NHẬP
INSERT INTO CHITIETPHIEUNHAP VALUES ('1','1',50,20000,'')

--HÓA ĐƠN 
INSERT INTO HOADON VALUES ('1','KH001','NV01','20/12/2022')
--CHI TIẾT HÓA ĐƠN
INSERT INTO CHITIET_HOADON VALUES ('1','1',100,20000,'')

--SELECT DATA
SELECT *FROM TK_QUANLY
SELECT *FROM TK_NHANVIEN
SELECT *FROM NHANVIEN
SELECT *FROM SACH
SELECT *FROM TACGIA
SELECT *FROM NHACUNGCAP
SELECT *FROM NHAXUATBAN
SELECT *FROM KHOHANG
SELECT *FROM KHUVUC
SELECT *FROM KHACHHANG
SELECT *FROM PHIEUNHAP
SELECT *FROM CHITIETPHIEUNHAP
SELECT *FROM HOADON
SELECT *FROM CHITIET_HOADON

