CREATE DATABASE QUANLY_NHASACH
GO
--DROP DATABASE QUANLY_NHASACH_
USE QUANLY_NHASACH
GO

--====================TẠO BẢNG================-
--TÀI KHOẢN QUẢN LÝ 
CREATE TABLE TK_QUANLY
(
	MAQL		VARCHAR(10),
	MATKHAU		NVARCHAR(60),
	CONSTRAINT PK_TKQL PRIMARY KEY (MAQL)
)
--TÀI KHOẢN NHÂN VIÊN
CREATE TABLE TK_NHANVIEN
(
	MANV		VARCHAR(10),
	MATKHAU		NVARCHAR(60),
	CONSTRAINT PK_TKNV PRIMARY KEY (MANV)
)
--NHÂN VIÊN 
CREATE TABLE NHANVIEN
(
	MANV		VARCHAR(10),
	TENNV		NVARCHAR(60),
	NGAYSINH	DATE,
	GIOITINH	NVARCHAR(5),
	CMND		VARCHAR(12),
	DIACHI		NVARCHAR(200),
	SDT			VARCHAR(12),
	CONSTRAINT PK_NHANVIEN PRIMARY KEY(MANV),
	CONSTRAINT FK_NHANVIEN_TKNV FOREIGN KEY(MANV) REFERENCES TK_NHANVIEN(MANV)

)
--KHO HÀNG
CREATE TABLE KHOHANG
(
	MAKHO		VARCHAR(10),
	TENKHO		NVARCHAR(200),
	DIACHI		NVARCHAR(200),
	SDT			VARCHAR(12),
	GHICHU		NVARCHAR(100)
	CONSTRAINT PK_KHOHANG PRIMARY KEY (MAKHO)
)
--NHÀ CUNG CẤP 
CREATE TABLE NHACUNGCAP
(
	MANCC		VARCHAR(10),
	TENNCC		NVARCHAR(200),
	DIACHI		NVARCHAR(200),
	SDT			VARCHAR(12),
	FAX			VARCHAR(10),
	EMAIL		NVARCHAR(100),
	CONSTRAINT PK_NHACUNGCAP PRIMARY KEY (MANCC)
)
--TÁC GIẢ 
CREATE TABLE TACGIA
(
	MATGCHINH	VARCHAR(10),
	TENTGCHINH	NVARCHAR(60),
	CONSTRAINT PK_TACGIA PRIMARY KEY(MATGCHINH)
)
--NHÀ XUẤT BẢN 
CREATE TABLE NHAXUATBAN
(
	MANXB		VARCHAR(10),
	TENNXB		NVARCHAR(100),
	CONSTRAINT PK_NXB PRIMARY KEY(MANXB)
)
--KHÁCH HÀNG
CREATE TABLE KHACHHANG
(
	MAKH		VARCHAR(10),
	TENKH		NVARCHAR(60),
	GIOITINH	NVARCHAR(5),
	DIACHI		NVARCHAR(200),
	SDT			VARCHAR(12),
	EMAIL		NVARCHAR(100),
	CONSTRAINT PK_KHACHHANG PRIMARY KEY (MAKH)
)
--SÁCH 
CREATE TABLE SACH
(
	MASH		VARCHAR(10),
	TENSH		NVARCHAR(100),
	THELOAI		NVARCHAR(50),
	GIA			FLOAT,
	SLTONKHO	INT,
	MANXB		VARCHAR(10),
	MATGCHINH	VARCHAR(10),
	MAKHO		VARCHAR(10),
	CONSTRAINT PK_SACH PRIMARY KEY(MASH),
	CONSTRAINT FK_SACH_NXB FOREIGN KEY(MANXB) REFERENCES NHAXUATBAN(MANXB),
	CONSTRAINT FK_SACH_TACGIA FOREIGN KEY(MATGCHINH) REFERENCES TACGIA(MATGCHINH),
	CONSTRAINT FK_SACH_KHO FOREIGN KEY(MAKHO) REFERENCES KHOHANG(MAKHO)
)
--PHIẾU NHẬP 
CREATE TABLE PHIEUNHAP
(
	MAPN		VARCHAR(10) ,
	MANV		VARCHAR(10),
	MANCC		VARCHAR(10),
	NGAYNHAP	DATETIME,
	CONSTRAINT PK_PHIEUNHAP PRIMARY KEY(MAPN),
	CONSTRAINT FK_PN_NV FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV),
	CONSTRAINT FK_PN_NCC FOREIGN KEY(MANCC) REFERENCES NHACUNGCAP(MANCC)
)
--CHI TIẾT PHIẾU NHẬP 
CREATE TABLE CHITIETPHIEUNHAP
(
	MAPN		VARCHAR(10) ,
	MASH		VARCHAR(10),
	SOLUONG		INT,
	DONGIA		FLOAT,
	THANHTIEN	FLOAT,
	CONSTRAINT PK_CTPN PRIMARY KEY(MAPN,MASH),
	CONSTRAINT FK_CTPN_PN FOREIGN KEY(MAPN) REFERENCES PHIEUNHAP(MAPN),
	CONSTRAINT FK_CTPN_SACH FOREIGN KEY(MASH) REFERENCES SACH(MASH)
)
--HÓA ĐƠN
CREATE TABLE HOADON 
(
	MAHD		VARCHAR(10),
	MAKH		VARCHAR(10),
	MANV		VARCHAR(10),
	NGAYXUATHD	DATETIME,
	CONSTRAINT PK_HOADON PRIMARY KEY(MAHD),
	CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH),
	CONSTRAINT FK_HOADON_NHANVIEN FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)
)
--CHI TIẾT HÓA ĐƠN 
CREATE TABLE CHITIET_HOADON
(
	MAHD		VARCHAR(10) ,
	MASH		VARCHAR(10),
	SOLUONG		INT,
	DONGIA		FLOAT,
	THANHTIEN	FLOAT,
	CONSTRAINT PK_CTHD PRIMARY KEY(MAHD,MASH),
	CONSTRAINT FK_CTHD_HOADON FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
	CONSTRAINT FK_CTHD_SACH FOREIGN KEY (MASH) REFERENCES SACH(MASH)
)
--KHU VỰC
CREATE TABLE KHUVUC 
(
	MAKV		VARCHAR(10),
	MASH		VARCHAR(10),
	VITRIKE		NVARCHAR(50),
	LAU			INT,
	CONSTRAINT PK_KHUVUC PRIMARY KEY (MAKV),
	CONSTRAINT FK_KHUVUC_SACH FOREIGN KEY (MASH) REFERENCES SACH(MASH)
)


--===============-TRIGGER - PROCEDURE- FUNCTION==================
--CREATE FUNCTION AUTO_IDSACH()
--RETURNS VARCHAR(10)
--AS
--BEGIN
--	DECLARE @ID VARCHAR(10)
--	IF (SELECT COUNT(MASH) FROM SACH) = 0
--		SET @ID = '0'
--	ELSE
--		SELECT @ID = MAX(RIGHT(MASH, 3)) FROM SACH
--		SELECT @ID = CASE
--			WHEN @ID >= 0 and @ID < 9 THEN 'SH00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
--			WHEN @ID >= 9 THEN 'SH0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
--		END
--	RETURN @ID
--END
--ALTER TABLE SACH 
-- ADD CONSTRAINT IDSACH DEFAULT DBO.AUTO_IDSACH()